Update UI changes
miguelgz36/SimulatorBacterialBiofilms pull request #48
Opened 2020-10-24 21:04 UTC by orozcojuan1998

2020-10-24 21:36 UTC, miguelgz36 approved these changes

2020-10-24 23:28 UTC, nicolasmira101 approved these changes

2020-10-25 02:21 UTC, adgarciaar requested changes
Screen blocked after click on Ok in widget indicating input error in MainMenu

2020-10-25 02:49 UTC, adgarciaar approved these changes

2020-10-25 02:49 UTC, merged