Feature/interface on execution
miguelgz36/SimulatorBacterialBiofilms pull request #65
Opened 2020-11-09 21:42 UTC by miguelgz36

2020-11-10 01:34 UTC, nicolasmira101 approved these changes

2020-11-10 23:48 UTC, adgarciaar requested changes
Resume the simulation when No is clicked in ConfirmExitWidget. In this moment, when Stop button is clicked, the simulation is stopped permanently

2020-11-11 00:40 UTC, adgarciaar approved these changes

2020-11-11 01:28 UTC, orozcojuan1998 approved these changes

2020-11-11 02:38 UTC, merged