first version of capture mini map to png
miguelgz36/SimulatorBacterialBiofilms pull request #71
Opened 2020-11-14 23:48 UTC by miguelgz36

2020-11-15 01:53 UTC, nicolasmira101 approved these changes

2020-11-15 23:56 UTC, adgarciaar requested changes
Save the screenshots in a folder different to Source. I think it could be a folder exclusive to that purpose.

2020-11-16 18:34 UTC, adgarciaar approved these changes

2020-11-16 19:37 UTC, orozcojuan1998 approved these changes

2020-11-16 19:37 UTC, merged