Latests gui improvements
miguelgz36/SimulatorBacterialBiofilms pull request #77
Opened 2020-11-21 17:27 UTC by orozcojuan1998

2020-11-21 17:48 UTC, adgarciaar requested changes
It is necessary to adjust image size and text (with scrolling) in DataSheetWidget

Change the label "Blocks long" or "Number of blocks" with "Length surface side" in both MainMenu and Confirmation

Change the label "Bacteria" with "Bacterium" in both MainMenu and Confirmation

In the instructions change the labels in this way:

1. Select a bacterium type
2. Select a surface type
3. Enable or disable the presimulation
4. Enter the value for the other parameters (if you want)
5. Start the simulation

In ConfirmationWidget, avoid the "," when showing for Simulation duration

In ConfirmationWidget, increase the size of the buttons (same size that in the other widgets) 

In MainMenuWidget the message "Please fill the params..." can be deleted

In AdvancedOptions change the word "options" with "parameters" in both main title and subtitle

In ConfirmationWidget change the message "Please verify your simulation..." with "Please verify the simulation parameters before starting it"

2020-11-21 20:09 UTC, orozcojuan1998 commented
Fixes are in progress

2020-11-22 17:41 UTC, adgarciaar approved these changes

2020-11-22 18:03 UTC, nicolasmira101 approved these changes

2020-11-22 18:37 UTC, miguelgz36 approved these changes

2020-11-22 18:37 UTC, merged